#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "URxvt" desktop=^1 follow=false
bspc rule -a "firefox" desktop=^2 follow=false
bspc rule -a "mpv" desktop=^3 follow=false
bspc rule -a "discord" desktop=^4 follow=false

pgrep -x polybar > /dev/null || polybar main &
xrdb ~/dotfiles/.Xresources
xcompmgr &
wal -R -a 85 &
