#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

pgrep -x polybar > /dev/null || polybar main &
xrdb ~/dotfiles/.Xresources
xcompmgr &
wal -R -a 85 &

counter=0
bspc query -D --names | while read -r name; do
  printf 'ws-icon-%i = ";<insert-icon-here>"\n' $((counter++)) 
done
